// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGbOi-W5pAK3VCKXmxQrWEgeuGC0AjUD8',
    appId: '1:431710987131:web:23b997fc401541303293de',
    messagingSenderId: '431710987131',
    projectId: 'part-delivery-request-6f2c',
    authDomain: 'part-delivery-request-6f2c.firebaseapp.com',
    storageBucket: 'part-delivery-request-6f2c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhbdRSD-D_8Z3uUFxZiiWJd7t8ycWi5iQ',
    appId: '1:431710987131:android:40f5f9775d4ed6673293de',
    messagingSenderId: '431710987131',
    projectId: 'part-delivery-request-6f2c',
    storageBucket: 'part-delivery-request-6f2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMYvKZxNup6oSCOyvI4GZNa7f8-aEWr_Q',
    appId: '1:431710987131:ios:97f2c04cf705d43d3293de',
    messagingSenderId: '431710987131',
    projectId: 'part-delivery-request-6f2c',
    storageBucket: 'part-delivery-request-6f2c.firebasestorage.app',
    iosBundleId: 'com.example.mobileApplicationDevelopemnt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMYvKZxNup6oSCOyvI4GZNa7f8-aEWr_Q',
    appId: '1:431710987131:ios:97f2c04cf705d43d3293de',
    messagingSenderId: '431710987131',
    projectId: 'part-delivery-request-6f2c',
    storageBucket: 'part-delivery-request-6f2c.firebasestorage.app',
    iosBundleId: 'com.example.mobileApplicationDevelopemnt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGbOi-W5pAK3VCKXmxQrWEgeuGC0AjUD8',
    appId: '1:431710987131:web:414762ad0098c5ce3293de',
    messagingSenderId: '431710987131',
    projectId: 'part-delivery-request-6f2c',
    authDomain: 'part-delivery-request-6f2c.firebaseapp.com',
    storageBucket: 'part-delivery-request-6f2c.firebasestorage.app',
  );
}
